### ISSUE TITLE
gemspec netconf dependency

### ISSUE THREAD

**Issue by routelastresort** [dgjnpr/Sloe#1]
Can you lock `gem.add_dependency('netconf', '>= 0.2.5')` to `0.3.x`, e.g. `('netconf', '~> 0.3.1')`, or an earlier version?  All new development (and CI testing) will focus on 1.9.3+ syntax, but 1.9.3 will also be EOLed 2/2015, so 2.0.0, 2.1.0 and beyond will be the only supported Ruby releases at that point.

**Comment by dgjnpr** [comment]
updating netconf version dependency to be a lot more relaxed. I am assuming that netconf gem will use semantic version - it looks like it does.
